# Seminar BA & QM
### Code Bol.com Case

Below you will find the code for the Bol.com case from group 8. 

Table of contents:

*  [Data preparation](#Data-preparation)
*  [Functions](#Functions)
*  [Models](#Models)

****

TO-DO:
-> determinantClassification toevoegen

CHECK:

NOTE:

In [688]:
import pandas as pd
import numpy as np
from datetime import date, timedelta, datetime
import time

import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

### Data Preparation
#### Load data and set data-types

In [689]:
#Import data
df_2019 = pd.read_csv('/Users/LV/Documents/ECONOMETRIE-ECO/MASTER/Seminar/2021_Case_Bol.com_Happy_Matches/data/data_2019.csv', low_memory = False)
df_2020 = pd.read_csv('/Users/LV/Documents/ECONOMETRIE-ECO/MASTER/Seminar/2021_Case_Bol.com_Happy_Matches/data/data_2020.csv', low_memory = False)

#Concat files and create new index
df_full = pd.concat([df_2019, df_2020])
df_full = df_full.reset_index(drop = True)

print('Total # records: ',df_full.shape[0])

Total # records:  4779466

In [690]:
#Rename columns
rename_columns = {'datetTimeFirstDeliveryMoment': 'dateTimeFirstDeliveryMoment',
                  'generalMatchClassification'  : 'detailedMatchClassification',
                  'detailedMatchClassification' : 'generalMatchClassification',
                  'quanityReturned'             : 'quantityReturned'}

df_full = df_full.rename(columns = rename_columns)

In [692]:
#Transform dates to date-type
df_full['orderDate']                   = pd.to_datetime(df_full['orderDate'])
df_full['cancellationDate']            = pd.to_datetime(df_full['cancellationDate'])
df_full['promisedDeliveryDate']        = pd.to_datetime(df_full['promisedDeliveryDate'])
df_full['shipmentDate']                = pd.to_datetime(df_full['shipmentDate'])
df_full['dateTimeFirstDeliveryMoment'] = pd.to_datetime(df_full['dateTimeFirstDeliveryMoment'])
df_full['startDateCase']               = pd.to_datetime(df_full['startDateCase'])
df_full['returnDateTime']              = pd.to_datetime(df_full['returnDateTime'])
df_full['registrationDateSeller']      = pd.to_datetime(df_full['registrationDateSeller'])

#Change type of columns
dtype = {'calculationDefinitive': bool,
         'noCancellation'       : bool,
         'noCase'               : bool,
         'hasOneCase'           : bool,
         'hasMoreCases'         : bool,
         'noReturn'             : bool}

df_full = df_full.astype(dtype)

#### Remove Noise

In [693]:
#Remove non-sensible rows
noise = df_full.loc[(df_full['startDateCase']        < df_full['orderDate']) | 
                   (df_full['cancellationDate']      < df_full['orderDate']) |
                   (df_full['promisedDeliveryDate']  < df_full['orderDate']) |
                   (df_full['shipmentDate']          < df_full['orderDate']) |
                   (df_full['returnDateTime']        < df_full['orderDate']) |
                   (df_full['cancellationDate']      > df_full['returnDateTime']) |
                   (df_full['shipmentDate']          > df_full['returnDateTime']) |
                   (df_full['orderDate']             < df_full['registrationDateSeller']) |
                   (df_full['orderDate']             > df_full['dateTimeFirstDeliveryMoment'].dt.normalize()) |
                   (df_full['cancellationDate']      > df_full['dateTimeFirstDeliveryMoment'].dt.normalize()) |
                   (df_full['shipmentDate']          > df_full['dateTimeFirstDeliveryMoment'].dt.normalize()) |
                   ((df_full['returnDateTime']       < df_full['dateTimeFirstDeliveryMoment'].dt.normalize()) & 
                                                       (df_full['dateTimeFirstDeliveryMoment'].notnull()) &
                                                       (df_full['returnDateTime'].notnull())) |
                   ((df_full['cancellationDate']     > df_full['shipmentDate']) &
                                                       ((df_full['cancellationReasonCode'] == 'CUST_FE') |
                                                       (df_full['cancellationReasonCode'] == 'CUST_CS'))) |
                   (df_full['registrationDateSeller'].isnull()) |
                   (df_full['promisedDeliveryDate'].isnull())].index

#Drop noise data
df = df_full.drop(index = noise)
print(len(noise), 'complete records removed from the data')
print('Cleaned # records: ',df.shape[0],'\n')

#Sort rows on orderDate and create new index
df = df.sort_values(by = 'orderDate')
df = df.reset_index(drop = True)

#Remove inconsistent values
cancellationNoise = df.loc[(df['noCancellation'] == True) & (df['cancellationDate'].notnull())].index
returnNoise       = df.loc[(df['noReturn'] == True) & (df['returnDateTime'].notnull())].index
caseNoise         = df.loc[(df['noCase'] == True) & (df['startDateCase'].notnull())].index
quantityNoise     = df.loc[df['quantityReturned'] > df['quantityOrdered']].index
deliveryNoise     = df.loc[(df['dateTimeFirstDeliveryMoment'].notnull()) & (df['onTimeDelivery'].isnull())].index

df.loc[cancellationNoise, ['cancellationDate','cancellationReasonCode']] = None
df.loc[returnNoise,       ['returnDateTime','quantityReturned','returnCode']] = None
df.loc[caseNoise,         ['startDateCase','cntDistinctCaseIds','hasOneCase','hasMoreCases']] = None
df.loc[quantityNoise,     ['quantityReturned']] = df.loc[quantityNoise, ['quantityOrdered']]
df.loc[deliveryNoise,     ['dateTimeFirstDeliveryMoment']] = None

print('# Records where cancellation values are emptied:',len(cancellationNoise))
print('# Records where return values are emptied: \t',len(returnNoise))
print('# Records where case values are emptied: \t',len(caseNoise))
print('# Records where quantity values are equalized: \t',len(quantityNoise))
print('# Records where delivery values are emptied: \t',len(deliveryNoise))

6516 complete records removed from the data
Cleaned # records:  4772950

# Records where cancellation values are emptied: 53780
# Records where return values are emptied: 	 8208
# Records where case values are emptied: 	 0
# Records where quantity values are equalized: 	 14722
# Records where delivery values are emptied: 	 4103

#### Create New Variables

##### Time Related

In [694]:
#Create new variables related to periods (days difference)
df['caseDays']             = (df['startDateCase'] - df['orderDate']).dt.days
df['returnDays']           = (df['returnDateTime'] - df['orderDate']).dt.days
df['cancellationDays']     = (df['cancellationDate'] - df['orderDate']).dt.days
df['actualDeliveryDays']   = (df['dateTimeFirstDeliveryMoment'].dt.normalize() - df['orderDate']).dt.days
df['shipmentDays']         = (df['shipmentDate'] - df['orderDate']).dt.days
df['partnerSellingMonths'] = (df['orderDate'] - df['registrationDateSeller']).dt.days
df['promisedDeliveryDays'] = (df['promisedDeliveryDate'] - df['orderDate']).dt.days

#Time related variables
df['orderYear']    = df['orderDate'].dt.year
df['orderMonth']   = df['orderDate'].dt.month
df['orderWeekday'] = df['orderDate'].dt.weekday
df['orderCorona']  = df['orderDate'].apply(lambda x: True if x > datetime.strptime('2020-03-20','%Y-%m-%d') else False)

#Create dummy variables for weekdays and months
df['orderMonday']    = df['orderWeekday'].apply(lambda x: True if x == 1 else False)
df['orderTuesday']   = df['orderWeekday'].apply(lambda x: True if x == 2 else False)
df['orderWednesday'] = df['orderWeekday'].apply(lambda x: True if x == 3 else False)
df['orderThursday']  = df['orderWeekday'].apply(lambda x: True if x == 4 else False)
df['orderFriday']    = df['orderWeekday'].apply(lambda x: True if x == 5 else False)
df['orderSaturday']  = df['orderWeekday'].apply(lambda x: True if x == 6 else False)
df['orderSunday']    = df['orderWeekday'].apply(lambda x: True if x == 7 else False)

df['orderJanuary']   = df['orderMonth'].apply(lambda x: True if x == 1 else False)
df['orderFebruary']  = df['orderMonth'].apply(lambda x: True if x == 2 else False)
df['orderMarch']     = df['orderMonth'].apply(lambda x: True if x == 3 else False)
df['orderApril']     = df['orderMonth'].apply(lambda x: True if x == 4 else False)
df['orderMay']       = df['orderMonth'].apply(lambda x: True if x == 5 else False)
df['orderJune']      = df['orderMonth'].apply(lambda x: True if x == 6 else False)
df['orderJuly']      = df['orderMonth'].apply(lambda x: True if x == 7 else False)
df['orderAugust']    = df['orderMonth'].apply(lambda x: True if x == 8 else False)
df['orderSeptember'] = df['orderMonth'].apply(lambda x: True if x == 9 else False)
df['orderOctober']   = df['orderMonth'].apply(lambda x: True if x == 10 else False)
df['orderNovember']  = df['orderMonth'].apply(lambda x: True if x == 11 else False)
df['orderDecember']  = df['orderMonth'].apply(lambda x: True if x == 12 else False)

##### Other

In [695]:
df['productTitleLength'] = len(df['productTitle'])

df['fulfilmentByBol'] = df['fulfilmentType'].apply(lambda x: True if x == 'FBB' else False)

df['countryCodeNL']   = df['countryCode'].apply(lambda x: True if x == 'NL' else False)
df['countryOriginNL'] = df['countryOriginSeller'].apply(lambda x: True if x == 'NL' else False)
df['countryOriginBE'] = df['countryOriginSeller'].apply(lambda x: True if x == 'BE' else False)
df['countryOriginDE'] = df['countryOriginSeller'].apply(lambda x: True if x == 'DE' else False)

##### Determinant Classification

##### Transporter

In [696]:
def transporterCluster(transporterCode):
    """
    Function to create a new manually clustered transporter variable: 28 -> 5 categories
    """
    if transporterCode in ['AH-NL','TNT','TNT-EXPRESS','TNT-EXTRA']:
        return 'POSTNL'
    elif transporterCode in ['DHL','DHL_DE','DHLFORYOU']:
        return 'DHL'
    elif transporterCode in ['DPD-NL','DPD-BE']:
        return 'DPD'
    elif transporterCode in ['BRIEFPOST','BPOST_BE','BPOST_BRIEF','DHL-GLOBAL-MAIL','TNT_BRIEF']:
        return 'BRIEFPOST'
    else:
        return 'OTHER'

In [697]:
df['transporterCodeGeneral'] = df['transporterCode'].apply(transporterCluster)
df['transporterCodeGeneral'].value_counts()

POSTNL       2110753
BRIEFPOST    1576462
DHL           436975
DPD           329746
OTHER         319014
Name: transporterCodeGeneral, dtype: int64

##### Product Group

In [698]:
def productGroupCluster(productGroup):
    """
    Function to create a new manually clustered product group variable based on categories bol.com
    60 -> 14 groups.
    """
    if productGroup in ['Dutch Books PG','Ebooks and Audiobooks','International Books PG']:
        return 'Books'
    elif productGroup in ['Games Accessories','Games Consoles','Games Software Physical',
                          'Movies','Music']:
        return 'Music, Film & Games'
    elif productGroup in ['Camera','Desktop Monitor and Beamer','Ereaders and Accessories',
                          'Laptop Computers','PC Accessories','Personal Audio',
                          'Sound and Vision Accessories','Storage and Network',
                          'Telephone and Tablet Accessories','Telephones and Tablets','Television']:
        return 'Computer & Electronics'
    elif productGroup in ['General Toys','Recreational and Outdoor Toys']:
        return 'Toys & Hobby'
    elif productGroup in ['Baby and Kids Fashion','Baby PG']:
        return 'Baby & Kids'
    elif productGroup in ['Daily Care PG','Health PG','Perfumery PG','Personal Care']:
        return 'Health & Care'
    elif productGroup in ['Footwear','Jewelry and Watches','Mens and Womens Fashion','Wearables']:
        return 'Fashion, Shoes & Accessories'
    elif productGroup in ['Bodyfashion and Beachwear','Camping and Outdoor','Cycling',
                          'Sporting Equipment','Sportswear','Travel Bags and Accessories']:
        return 'Sports, Outdoor & Travel'
    elif productGroup in ['Educational Dutch','Educational International','Printing and Ink']:
        return 'Office & School'
    elif productGroup in ['Supermarket PG'] :
        return 'Food & Beverage'
    elif productGroup in ['Furniture','Heating and Air','Home Decoration','Home Entertainment',
                          'Household','Household Appliances','Kitchen','Kitchen Machines',
                          'Lighting','Major Domestic Appliances PG','Plumbing and Safety']:
        return 'Home, Cooking & Household'
    elif productGroup in ['Garden','Pet PG','Textiles','Tools and Paint']:
        return 'Pets, Garden & Jobs'
    elif productGroup in ['Car and Motorcycle'] :
        return 'Car & Motor'
    else:
        return 'Other'

In [699]:
df['productGroupGeneral'] = df['productGroup'].apply(productGroupCluster)
df['productGroupGeneral'].value_counts()

Computer & Electronics          1387679
Home, Cooking & Household        797874
Sports, Outdoor & Travel         522098
Toys & Hobby                     500977
Pets, Garden & Jobs              339813
Health & Care                    299049
Food & Beverage                  258769
Books                            184581
Music, Film & Games              163842
Baby & Kids                      113707
Fashion, Shoes & Accessories     110067
Office & School                   52270
Car & Motor                       29753
Other                             12471
Name: productGroupGeneral, dtype: int64

In [700]:
#Create dummies of new product grouping
for group in df['productGroupGeneral'].unique():
    
    columnName = 'group' + group.split(' ')[0].replace(',','')
    df[columnName] = df['productGroupGeneral'].apply(lambda x: True if x == group else False)

##### Total Columns

In [701]:
print(df.columns)
print('Total: ',len(df.columns),' columns')

Index(['orderDate', 'productId', 'sellerId', 'totalPrice', 'quantityOrdered',
       'countryCode', 'cancellationDate', 'cancellationReasonCode',
       'promisedDeliveryDate', 'shipmentDate', 'transporterCode',
       'transporterName', 'transporterNameOther',
       'dateTimeFirstDeliveryMoment', 'fulfilmentType', 'startDateCase',
       'cntDistinctCaseIds', 'returnDateTime', 'quantityReturned',
       'returnCode', 'productTitle', 'brickName', 'chunkName', 'productGroup',
       'productSubGroup', 'productSubSubGroup', 'registrationDateSeller',
       'countryOriginSeller', 'currentCountryAvailabilitySeller',
       'calculationDefinitive', 'noCancellation', 'onTimeDelivery', 'noCase',
       'hasOneCase', 'hasMoreCases', 'noReturn', 'detailedMatchClassification',
       'generalMatchClassification', 'caseDays', 'returnDays',
       'cancellationDays', 'actualDeliveryDays', 'shipmentDays',
       'partnerSellingMonths', 'promisedDeliveryDays', 'orderYear',
       'orderMonth', 'orderWeekday', 'orderCorona', 'orderMonday',
       'orderTuesday', 'orderWednesday', 'orderThursday', 'orderFriday',
       'orderSaturday', 'orderSunday', 'orderJanuary', 'orderFebruary',
       'orderMarch', 'orderApril', 'orderMay', 'orderJune', 'orderJuly',
       'orderAugust', 'orderSeptember', 'orderOctober', 'orderNovember',
       'orderDecember', 'productTitleLength', 'fulfilmentByBol',
       'countryCodeNL', 'countryOriginNL', 'countryOriginBE',
       'countryOriginDE', 'transporterCodeGeneral', 'productGroupGeneral',
       'groupHealth', 'groupHome', 'groupSports', 'groupComputer', 'groupPets',
       'groupToys', 'groupBooks', 'groupBaby', 'groupMusic', 'groupFood',
       'groupOffice', 'groupFashion', 'groupOther', 'groupCar'],
      dtype='object')
Total:  90  columns

In [703]:
WEEK = ['orderMonday','orderTuesday','orderWednesday','orderThursday','orderFriday','orderSaturday','orderSunday']
MONTH = ['orderJanuary','orderFebruary','orderMarch','orderApril','orderMay','orderJune',
         'orderJuly','orderAugust','orderSeptember','orderOctober','orderNovember','orderDecember']
BASIC = ['totalPrice','quantityOrdered','fulfilmentByBol','countryCodeNL','countryOriginNL','countryOriginBE',
        'countryOriginDE','productTitleLength']
GROUP = ['groupHealth','groupHome','groupSports','groupComputer','groupPets','groupToys','groupBooks', 
         'groupBaby', 'groupMusic', 'groupFood','groupOffice','groupFashion','groupOther','groupCar']

### Functions

In [654]:
def addPeriodColumns(df,X):
    """
    Function to create columns which indicate whether determinants are known after X days.
    Input: X = number of days after order date at which the prediction is made
           df = dataFrame
    """
    
    df['caseKnown']           = df.apply(lambda row: True if row.caseDays <= X else False, axis = 1)
    df['returnKnown']         = df.apply(lambda row: True if row.returnDays <= X else False, axis = 1)
    df['cancellationKnown']   = df.apply(lambda row: True if row.cancellationDays <= X else False, axis = 1)
    df['onTimeDeliveryKnown'] = df.apply(lambda row: True if ((row.actualDeliveryDays <= X) and (row.onTimeDelivery == True)) else False, axis = 1)
    df['lateDeliveryKnown']   = df.apply(lambda row: True if ((row.actualDeliveryDays <= X) and (row.onTimeDelivery == False)) else False, axis = 1)
    
    for transporter in df['transporterCodeGeneral'].unique():
        dummyColumn = 'transporter' + transporter
        df[dummyColumn] = df.apply(lambda row: True if ((row.shipmentDays <= X) and (row.transporterCodeGeneral == transporter)) else False, axis = 1)

    return df

In [572]:
def addProductColumns(df):
    """
    Function to add 4 columns: productOrderCount, productTotalCount, productTotalReturned and productReturnFraction.
    Input: dataFrame with columns: 'productId','orderDate','quantityOrdered','quantityReturned','returnDateTime'.
    """
    df = df.sort_values(by = ['productId','orderDate'])
    df = df.reset_index(drop = True)
    
    df_ = df[['productId','orderDate','quantityOrdered','quantityReturned','returnDateTime']]
    
    #ProductTotalCount
    pivot = df_.groupby(['productId','orderDate']).quantityOrdered.sum().groupby('productId').cumsum()
    productTotalCount = df_.merge(pivot, 
                                left_on=['productId','orderDate'], 
                                right_index=True, 
                                how = 'left').quantityOrdered_y
    
    #ProductOrderCount
    pivot = df_.groupby(['productId','orderDate']).quantityOrdered.count().groupby('productId').cumsum()
    productOrderCount = df_.merge(pivot, 
                                left_on=['productId','orderDate'], 
                                right_index=True, 
                                how = 'left').quantityOrdered_y
    
    #ProductTotalReturned
    productTotalReturned = np.zeros(df_.shape[0])
    
    previousID = None
    
    returnDic = {}
    
    for row in df_.itertuples(): #iterate through dataFrame
        
        if row[0] == 0: 
            
            #update return dictionary if this product is returned
            if row[4] != None:
                if row[5] in returnDic:
                    returnDic[row[5]] += row[4]
                else:
                    returnDic[row[5]] = row[4]

            previousID = row[1]
            
        elif (previousID == row[1]):
            
            #update return dictionary if this product is returned
            if row[4] != None:
                if row[5] in returnDic:
                    returnDic[row[5]] += row[4]
                else:
                    returnDic[row[5]] = row[4]
            
            #add returned products to new dictionary if known
            known = {k: v for k, v in returnDic.items() if k <= row[2]}
            productTotalReturned[row[0]] = sum(known.values())
            
            #update the dictionary by removing the returns which are now known
            returnDic = {k: v for k, v in returnDic.items() if k > row[2]}
                        
            previousID = row[1]
            
        else:
            returnDic = {} #new productId, hence empty the return dictionary
            
            #update return dictionary if this product is returned
            if row[4] != None:
                if row[5] in returnDic:
                    returnDic[row[5]] += row[4]
                else:
                    returnDic[row[5]] = row[4]
                    
            previousID = row[1]
    
    df_['productTotalReturned'] = productTotalReturned
    pivot = df_.groupby(by = ['productId','orderDate']).productTotalReturned.sum().groupby('productId').cumsum()
    productTotalReturned = df_.merge(pivot, 
                                left_on=['productId','orderDate'], 
                                right_index=True, 
                                how = 'left').productTotalReturned_y
     
    #Add new columns to dataFrame    
    df['productOrderCount'] = productOrderCount
    df['productTotalCount'] = productTotalCount
    df['productTotalReturned'] = productTotalReturned
    df['productReturnFraction'] = productTotalReturned / productTotalCount
    
    return(df)

In [461]:
# def addProductCount_OLD(df):
#     """
#     Fuction to add a column to your dataframe which counts the number of occurances of
#     the productId uptil that date and total quantityOrdered.
#     Now 26 minutes for 1,000,000 rows
#     """
#     df = df.sort_values(by = ['productId','orderDate'])
#     df = df.reset_index(drop = True)
    
#     df_ = df[['productId','orderDate','quantityOrdered','quantityReturned','returnDateTime']]
    
#     ID_list = df_.productId.value_counts().sort_index().cumsum()
#     #count_ID = 0
    
#     productOrderCount = np.ones(df_.shape[0])
#     productTotalCount = np.zeros(df_.shape[0])
#     productTotalReturned = np.zeros(df.shape[0])
    
#     for row in df_.itertuples():
        
#         if row[0] == 0:
#             #df_P = df_.loc[df_['productId'] == row[1]]
#             #df_P = df_.iloc[:ID_list.iloc[count_ID]]
#             df_P = df_.iloc[:ID_list.loc[row[1]]]
            
#             productTotalCount[row[0]] = row[3]
            
#             previousId = row[1]
            
#         elif previousId == row[1]:
#             extract = df_P.loc[df_P['orderDate'] <= row[2]]
#             extract2 = extract.loc[extract['returnDateTime'] <= row[2]]
            
#             productOrderCount[row[0]] = extract.quantityOrdered.count()
#             productTotalCount[row[0]] = extract.quantityOrdered.sum()
#             productTotalReturned[row[0]] = extract2.quantityReturned.sum()
            
#             previousId = row[1]
            
#         else:
#             #df_P = df_.loc[df_['productId'] == row[1]]
#             #df_P = df_.iloc[ID_list.iloc[count_ID]:ID_list.iloc[count_ID+1]]
#             df_P = df_.iloc[ID_list.loc[previousId]:ID_list.loc[row[1]]]
            
#             extract = df_P.loc[df_P['orderDate'] <= row[2]]
#             extract2 = extract.loc[extract['returnDateTime'] <= row[2]]
            
#             productOrderCount[row[0]] = extract.quantityOrdered.count()
#             productTotalCount[row[0]] = extract.quantityOrdered.sum()
#             productTotalReturned[row[0]] = extract2.quantityReturned.sum()
            
#             previousId = row[1]
#             #count_ID += 1
               
#     df['productOrderCount'] = productOrderCount
#     df['productTotalCount'] = productTotalCount
#     df['productTotalReturned'] = productTotalReturned
#     df['productReturnFraction'] = productTotalReturned / productTotalCount
    
#     return(df)

#### TESTING

In [ ]:
#df.loc[(df['productId'] == 9300000000762808) | (df['productId'] == 9200000101821794)]
#df.loc[(df['productId'] == 9200000105019922)]
#[['productId','orderDate','returnDateTime','quantityOrdered','quantityReturned']]
#[['caseDays','returnDays','cancellationDays','actualDeliveryDays']]

# t0 = time.time()
# a = addProductColumns(df)
# t1 = time.time()
# total = t1-t0
# print(total)

In [662]:
df_ = df.loc[(df['productId'] == 9300000000762808) | (df['productId'] == 9200000101821794)]
#df_ = df.loc[(df['productId'] == 9200000105019922)]
df_ = df_[['productId','orderDate','returnDateTime','quantityOrdered','quantityReturned',
           'caseDays','returnDays','cancellationDays','actualDeliveryDays','onTimeDelivery',
           'transporterCodeGeneral','shipmentDays']]

df_ = addProductColumns(df_)
df_ = addPeriodColumns(df_,2)

<ipython-input-572-58034f0a03de>:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_['productTotalReturned'] = productTotalReturned

,productId,orderDate,returnDateTime,quantityOrdered,quantityReturned,caseDays,returnDays,cancellationDays,actualDeliveryDays,onTimeDelivery,...,caseKnown,returnKnown,cancellationKnown,onTimeDeliveryKnown,lateDeliveryKnown,transporterPOSTNL,transporterBRIEFPOST,transporterOTHER,transporterDHL,transporterDPD
0,9200000101821794,2019-02-19,NaT,1,NaN,NaN,NaN,NaN,1.0,True,...,False,False,False,True,False,True,False,False,False,False
1,9200000101821794,2019-02-20,NaT,1,NaN,NaN,NaN,NaN,1.0,True,...,False,False,False,True,False,True,False,False,False,False
2,9200000101821794,2019-03-19,NaT,1,NaN,NaN,NaN,NaN,1.0,True,...,False,False,False,True,False,True,False,False,False,False
3,9200000101821794,2019-04-02,NaT,1,NaN,NaN,NaN,NaN,1.0,True,...,False,False,False,True,False,True,False,False,False,False
4,9200000101821794,2019-04-14,NaT,1,NaN,NaN,NaN,NaN,1.0,True,...,False,False,False,True,False,True,False,False,False,False
5,9200000101821794,2019-05-05,NaT,1,NaN,NaN,NaN,NaN,1.0,True,...,False,False,False,True,False,True,False,False,False,False
6,9200000101821794,2019-06-09,NaT,1,NaN,NaN,NaN,NaN,2.0,True,...,False,False,False,True,False,True,False,False,False,False
7,9200000101821794,2019-06-10,NaT,1,NaN,NaN,NaN,NaN,2.0,False,...,False,False,False,False,True,False,True,False,False,False
8,9200000101821794,2019-06-16,NaT,1,NaN,NaN,NaN,NaN,1.0,True,...,False,False,False,True,False,True,False,False,False,False
9,9200000101821794,2019-06-17,NaT,1,NaN,NaN,NaN,NaN,1.0,True,...,False,False,False,True,False,True,False,False,False,False
10,9200000101821794,2019-07-16,NaT,1,NaN,NaN,NaN,NaN,2.0,True,...,False,False,False,True,False,False,True,False,False,False
11,9200000101821794,2019-07-22,NaT,1,NaN,NaN,NaN,NaN,1.0,True,...,False,False,False,True,False,True,False,False,False,False
12,9200000101821794,2019-07-29,NaT,1,NaN,NaN,NaN,NaN,NaN,NaN,...,False,False,False,False,False,False,False,False,False,False
13,9200000101821794,2019-08-21,NaT,1,NaN,NaN,NaN,NaN,1.0,True,...,False,False,False,True,False,True,False,False,False,False
14,9200000101821794,2019-09-12,NaT,1,NaN,NaN,NaN,NaN,1.0,True,...,False,False,False,True,False,True,False,False,False,False
15,9200000101821794,2019-09-21,NaT,1,NaN,NaN,NaN,NaN,2.0,True,...,False,False,False,True,False,True,False,False,False,False
16,9200000101821794,2019-09-22,NaT,1,NaN,NaN,NaN,NaN,1.0,True,...,False,False,False,True,False,True,False,False,False,False
17,9200000101821794,2019-10-19,NaT,1,NaN,NaN,NaN,NaN,2.0,True,...,False,False,False,True,False,True,False,False,False,False
18,9200000101821794,2019-10-22,NaT,1,NaN,NaN,NaN,NaN,1.0,True,...,False,False,False,True,False,True,False,False,False,False
19,9200000101821794,2019-10-31,NaT,1,NaN,NaN,NaN,NaN,1.0,True,...,False,False,False,True,False,True,False,False,False,False
20,9200000101821794,2019-11-07,NaT,1,NaN,NaN,NaN,NaN,1.0,True,...,False,False,False,True,False,True,False,False,False,False
21,9200000101821794,2020-04-18,2020-04-23,1,NaN,NaN,5.0,NaN,2.0,True,...,False,False,False,True,False,True,False,False,False,False
22,9200000101821794,2020-04-21,NaT,1,NaN,NaN,NaN,NaN,1.0,True,...,False,False,False,True,False,False,False,False,True,False
23,9200000101821794,2020-04-22,NaT,1,NaN,NaN,NaN,NaN,1.0,True,...,False,False,False,True,False,True,False,False,False,False
24,9300000000762808,2020-05-17,NaT,3,NaN,NaN,NaN,NaN,3.0,True,...,False,False,False,False,False,False,False,False,True,False
25,9300000000762808,2020-05-21,NaT,1,NaN,NaN,NaN,NaN,NaN,NaN,...,False,False,False,False,False,False,True,False,False,False
26,9300000000762808,2020-05-21,NaT,1,NaN,NaN,NaN,NaN,NaN,NaN,...,False,False,False,False,False,False,True,False,False,False
27,9300000000762808,2020-05-25,NaT,2,NaN,NaN,NaN,NaN,3.0,False,...,False,False,False,False,False,False,False,False,True,False
28,9300000000762808,2020-05-26,NaT,4,NaN,NaN,NaN,NaN,2.0,True,...,False,False,False,True,False,False,False,False,True,False
29,9300000000762808,2020-05-28,NaT,2,NaN,NaN,NaN,NaN,NaN,NaN,...,False,False,False,False,False,False,True,False,False,False
30,9300000000762808,2020-05-28,NaT,2,NaN,NaN,NaN,NaN,1.0,True,...,False,False,False,True,False,False,False,False,False,True
31,9300000000762808,2020-05-31,NaT,1,NaN,NaN,NaN,NaN,NaN,NaN,...,False,False,False,False,False,False,True,False,False,False
32,9300000000762808,2020-06-03,NaT,2,NaN,NaN,NaN,NaN,NaN,NaN,...,False,False,False,False,False,False,True,False,False,False
33,9300000000762808,2020-06-08,NaT,1,NaN,NaN,NaN,NaN,NaN,NaN,...,False,False,False,False,False,False,True,False,False,False
34,9300000000762808,2020-06-18,2020-06-20,1,1.0,NaN,2.0,NaN,NaN,NaN,...,False,True,False,False,False,False,True,False,False,False
35,9300000000762808,2020-07-05,NaT,1,NaN,NaN,NaN,NaN,NaN,NaN,...,False,False,False,False,False,False,True,False,False,False
36,9300000000762808,2020-07-08,NaT,1,NaN,NaN,NaN,NaN,NaN,NaN,...,False,False,False,False,False,False,True,False,False,False
37,9300000000762808,2020-08-22,NaT,2,NaN,NaN,NaN,NaN,3.0,True,...,False,False,False,False,False,False,False,False,True,False
38,9300000000762808,2020-08-31,NaT,4,NaN,NaN,NaN,NaN,1.0,True,...,False,False,False,True,False,False,False,False,True,False
39,9300000000762808,2020-09-16,2020-09-22,1,1.0,NaN,6.0,NaN,NaN,NaN,...,False,False,False,False,False,False,True,False,False,False
40,9300000000762808,2020-09-16,NaT,2,NaN,NaN,NaN,NaN,NaN,NaN,...,False,False,False,False,False,False,True,False,False,False
41,9300000000762808,2020-10-12,NaT,2,NaN,NaN,NaN,NaN,NaN,NaN,...,False,False,False,False,False,False,True,False,False,False
42,9300000000762808,2020-11-06,NaT,1,NaN,NaN,NaN,NaN,NaN,NaN,...,False,False,False,False,False,False,True,False,False,False
43,9300000000762808,2020-11-14,NaT,6,NaN,NaN,NaN,NaN,NaN,NaN,...,False,False,False,False,False,False,False,False,False,False
44,9300000000762808,2020-11-23,NaT,1,NaN,NaN,NaN,NaN,NaN,NaN,...,False,False,False,False,False,False,True,False,False,False
45,9300000000762808,2020-12-07,NaT,2,NaN,NaN,NaN,NaN,2.0,True,...,False,False,False,True,False,False,False,False,False,True
46,9300000000762808,2020-12-13,NaT,2,NaN,NaN,NaN,NaN,2.0,True,...,False,False,False,True,False,False,False,False,False,True
47,9300000000762808,2020-12-13,NaT,1,NaN,NaN,NaN,NaN,NaN,NaN,...,False,False,False,False,False,False,True,False,False,False

### Models